services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: capability-map-backend
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: capability-map-frontend
    depends_on:
      - backend
    ports:
      - "8082:8080"
